#!/bin/bash
function extport() {
  if [[ -f $1 ]]; then
  ports=$(cat $1 | grep -oP "^\d{1,5}" | tr "\n" "," | sed "s/,$//" )
  echo "${ports}" | xclip -i -sel clip
  notify-send "Ports copied!"
  fi
}

